<?php
declare(strict_types=1);

/**
 * Secure asset proxy for forecast dashboard.
 * Serves generated charts and interactive HTML files that live outside /public.
 */

session_start();

header('Cache-Control: no-cache, no-store, must-revalidate, max-age=0');
header('Pragma: no-cache');
header('Expires: 0');
header('Access-Control-Allow-Origin: *');
header('X-Content-Type-Options: nosniff');

$root = realpath(__DIR__ . '/../../assets/reports-model');
$chartsDir = $root ? $root . DIRECTORY_SEPARATOR . 'charts' : null;

$assets = [
    // Forecast static charts (PNG)
    'supply' => [
        'path' => $chartsDir ? $chartsDir . DIRECTORY_SEPARATOR . 'supply_forecast.png' : null,
        'mime' => 'image/png',
        'label' => 'Forecasted Blood Supply chart',
    ],
    'demand' => [
        'path' => $chartsDir ? $chartsDir . DIRECTORY_SEPARATOR . 'demand_forecast.png' : null,
        'mime' => 'image/png',
        'label' => 'Forecasted Hospital Demand chart',
    ],
    'comparison' => [
        'path' => $chartsDir ? $chartsDir . DIRECTORY_SEPARATOR . 'supply_vs_demand.png' : null,
        'mime' => 'image/png',
        'label' => 'Supply vs Demand chart',
    ],
    'projected_stock' => [
        'path' => $chartsDir ? $chartsDir . DIRECTORY_SEPARATOR . 'projected_stock.png' : null,
        'mime' => 'image/png',
        'label' => 'Projected Stock chart',
    ],

    // Forecast interactive HTML views
    'interactive_supply' => [
        'path' => $root ? $root . DIRECTORY_SEPARATOR . 'interactive_supply.html' : null,
        'mime' => 'text/html; charset=UTF-8',
        'label' => 'Interactive Supply Trend',
    ],
    'interactive_demand' => [
        'path' => $root ? $root . DIRECTORY_SEPARATOR . 'interactive_demand.html' : null,
        'mime' => 'text/html; charset=UTF-8',
        'label' => 'Interactive Demand Trend',
    ],
    'interactive_combined' => [
        'path' => $root ? $root . DIRECTORY_SEPARATOR . 'interactive_combined.html' : null,
        'mime' => 'text/html; charset=UTF-8',
        'label' => 'Interactive Supply vs Demand view',
    ],
    'projected_stock_html' => [
        'path' => $root ? $root . DIRECTORY_SEPARATOR . 'projected_stock.html' : null,
        'mime' => 'text/html; charset=UTF-8',
        'label' => 'Projected Stock Status view',
    ],

    // Donor & hospital overview interactive HTML charts (generated by reports_dashboard_overview.py)
    'donor_age' => [
        'path' => $chartsDir ? $chartsDir . DIRECTORY_SEPARATOR . 'donor_age_distribution.html' : null,
        'mime' => 'text/html; charset=UTF-8',
        'label' => 'Donor Age Distribution chart',
    ],
    'donor_location' => [
        'path' => $chartsDir ? $chartsDir . DIRECTORY_SEPARATOR . 'donor_location_distribution.html' : null,
        'mime' => 'text/html; charset=UTF-8',
        'label' => 'Donor Location Distribution chart',
    ],
    'donor_sex' => [
        'path' => $chartsDir ? $chartsDir . DIRECTORY_SEPARATOR . 'donor_sex_distribution.html' : null,
        'mime' => 'text/html; charset=UTF-8',
        'label' => 'Donor Sex Distribution chart',
    ],
    'donor_eligibility' => [
        'path' => $chartsDir ? $chartsDir . DIRECTORY_SEPARATOR . 'donor_eligibility_status.html' : null,
        'mime' => 'text/html; charset=UTF-8',
        'label' => 'Donor Eligibility Status chart',
    ],
    'donor_blood_type' => [
        'path' => $chartsDir ? $chartsDir . DIRECTORY_SEPARATOR . 'donor_blood_type_distribution.html' : null,
        'mime' => 'text/html; charset=UTF-8',
        'label' => 'Donor Blood Type Distribution chart',
    ],
    'donation_frequency' => [
        'path' => $chartsDir ? $chartsDir . DIRECTORY_SEPARATOR . 'donation_frequency.html' : null,
        'mime' => 'text/html; charset=UTF-8',
        'label' => 'Donation Frequency chart',
    ],
    'donations_by_month' => [
        'path' => $chartsDir ? $chartsDir . DIRECTORY_SEPARATOR . 'donations_by_month.html' : null,
        'mime' => 'text/html; charset=UTF-8',
        'label' => 'Donations by Month chart',
    ],
    'mobile_vs_inhouse' => [
        'path' => $chartsDir ? $chartsDir . DIRECTORY_SEPARATOR . 'mobile_vs_inhouse.html' : null,
        'mime' => 'text/html; charset=UTF-8',
        'label' => 'Mobile Drive vs In-House Donations chart',
    ],
    'successful_vs_unsuccessful' => [
        'path' => $chartsDir ? $chartsDir . DIRECTORY_SEPARATOR . 'successful_vs_unsuccessful.html' : null,
        'mime' => 'text/html; charset=UTF-8',
        'label' => 'Successful vs Unsuccessful Donations chart',
    ],
    'monthly_requests_trend' => [
        'path' => $chartsDir ? $chartsDir . DIRECTORY_SEPARATOR . 'monthly_blood_requests_trend.html' : null,
        'mime' => 'text/html; charset=UTF-8',
        'label' => 'Monthly Blood Requests Trend chart',
    ],
    'requests_by_blood_type' => [
        'path' => $chartsDir ? $chartsDir . DIRECTORY_SEPARATOR . 'blood_requests_by_type.html' : null,
        'mime' => 'text/html; charset=UTF-8',
        'label' => 'Requests by Blood Type chart',
    ],
];

$key = $_GET['asset'] ?? '';

if (!isset($assets[$key])) {
    http_response_code(400);
    header('Content-Type: text/plain; charset=UTF-8');
    echo "Invalid asset requested.";
    exit;
}

$asset = $assets[$key];
$path = $asset['path'];

if (!$path || !file_exists($path)) {
    http_response_code(404);
    header('Content-Type: text/html; charset=UTF-8');
    echo '<!DOCTYPE html><html><body style="font-family:Arial,sans-serif;padding:16px;">';
    echo '<h3 style="color:#941022;margin-top:0;">' . htmlspecialchars($asset['label']) . '</h3>';
    echo '<p style="margin-bottom:0;">This asset has not been generated yet. Please click "Refresh Data" in the dashboard to regenerate forecasts.</p>';
    echo '</body></html>';
    exit;
}

$mime = $asset['mime'];
header('Content-Type: ' . $mime);
header('Content-Length: ' . filesize($path));

$stream = fopen($path, 'rb');
if ($stream !== false) {
    fpassthru($stream);
    fclose($stream);
} else {
    http_response_code(500);
    header('Content-Type: text/plain; charset=UTF-8');
    echo 'Unable to read asset.';
}



